#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Aug 28 21:29:54 EDT 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_segment_behav -key {Behavioral:sim_1:Functional:tb_segment} -tclbatch tb_segment.tcl -view /home/alex/FPGALAB/Lab1/lab1/tb_segment_behav.wcfg -log simulate.log"
xsim tb_segment_behav -key {Behavioral:sim_1:Functional:tb_segment} -tclbatch tb_segment.tcl -view /home/alex/FPGALAB/Lab1/lab1/tb_segment_behav.wcfg -log simulate.log

